# Generated by Django 3.0.6 on 2020-06-04 22:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_auto_20200604_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('study_instance_uid', models.CharField(max_length=200)),
                ('study_id', models.CharField(blank=True, max_length=200)),
                ('study_date', models.CharField(blank=True, max_length=100)),
                ('report_created', models.DateTimeField(blank=True, null=True)),
                ('report_name', models.CharField(blank=True, max_length=100)),
                ('advanced_report', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='patients.Patient')),
            ],
        ),
    ]
