# Generated by Django 3.0.6 on 2020-06-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '__first__'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.DecimalField(blank=True, decimal_places=3, max_digits=5)),
                ('dob', models.DateField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
