# Generated by Django 3.0.3 on 2020-06-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200604_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5),
        ),
    ]
