# Generated by Django 3.0.3 on 2020-04-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='organization name')),
                ('address_line1', models.CharField(max_length=200, verbose_name='address line 1')),
                ('address_line2', models.CharField(max_length=200, verbose_name='address line 2')),
                ('address_city', models.CharField(max_length=100, verbose_name='address city')),
                ('address_state', models.CharField(max_length=100, verbose_name='address state')),
                ('address_zip', models.CharField(max_length=30, verbose_name='address zip')),
                ('address_country', models.CharField(max_length=50, verbose_name='address country')),
                ('phone', models.CharField(max_length=100, verbose_name='organization phone number')),
            ],
        ),
    ]
