# Generated by Django 3.0.3 on 2020-05-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='organization phone'),
        ),
    ]
