# Generated by Django 3.0.3 on 2020-04-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200420_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200, verbose_name='address line 2'),
        ),
    ]
