# Generated by Django 3.0.3 on 2020-06-16 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_auto_20200604_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image_study_instance_uid', models.CharField(max_length=200)),
                ('image_study_id', models.CharField(blank=True, max_length=200)),
                ('image_study_date', models.CharField(blank=True, max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagestudies', to='patients.Patient')),
            ],
        ),
    ]
