# Generated by Django 3.0.3 on 2020-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagestudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestudy',
            name='dicom_patient_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
